CREATE TABLE fns_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    received_timestamp DATETIME(6) NOT NULL,
    hostname VARCHAR(255) NOT NULL,
    os VARCHAR(50) NOT NULL,
    event_timestamp DATETIME NOT NULL,
    rule_uuid CHAR(36) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    source VARCHAR(45) NOT NULL,
    destination VARCHAR(45) NOT NULL,
    protocol VARCHAR(10) NOT NULL,
    source_port INT UNSIGNED NOT NULL,
    destination_port INT UNSIGNED NOT NULL,
    action VARCHAR(20) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    originator_packets BIGINT UNSIGNED NOT NULL,
    originator_bytes BIGINT UNSIGNED NOT NULL,
    reply_packets BIGINT UNSIGNED NOT NULL,
    reply_bytes BIGINT UNSIGNED NOT NULL,
    description TEXT NULL,
    INDEX idx_received_timestamp (received_timestamp),
    INDEX idx_hostname (hostname),
    INDEX idx_event_timestamp (event_timestamp),
    INDEX idx_rule_uuid (rule_uuid),
    INDEX idx_source (source),
    INDEX idx_destination (destination),
    INDEX idx_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;